=== lpugin/rism-online-renderer/schemas/work.schema-no-extra.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "definitions": {
        "I18nData": {
            "additionalProperties": {
                "items": {
                    "type": "string"
                },
                "type": "array"
            },
            "description": "Label object for multilingual strings",
            "type": "object"
        },
        "WorkTypes.CreatedData": {
            "additionalProperties": false,
            "properties": {
                "label": {
                    "$ref": "#/definitions/I18nData"
                },
                "value": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "WorkTypes.CreatorData": {
            "additionalProperties": false,
            "properties": {
                "relatedTo": {
                    "$ref": "#/definitions/WorkTypes.RelatedToData"
                },
                "role": {
                    "$ref": "#/definitions/WorkTypes.RoleData"
                }
            },
            "type": "object"
        },
        "WorkTypes.EncodingsData": {
            "additionalProperties": false,
            "properties": {
                "data": {
                    "$ref": "#/definitions/WorkTypes.PAEData"
                },
                "format": {
                    "type": "string"
                },
                "label": {
                    "$ref": "#/definitions/I18nData"
                },
                "url": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "WorkTypes.ExternalAuthoritiesData": {
            "additionalProperties": false,
            "properties": {
                "items": {
                    "items": {
                        "$ref": "#/definitions/WorkTypes.ExternalAuthoritiesItemData"
                    },
                    "type": "array"
                },
                "label": {
                    "$ref": "#/definitions/I18nData"
                },
                "type": {
                    "type": "string"
                }
            },
            "required": [
                "items"
            ],
            "type": "object"
        },
        "WorkTypes.ExternalAuthoritiesItemData": {
            "additionalProperties": false,
            "properties": {
                "base": {
                    "type": "string"
                },
                "label": {
                    "$ref": "#/definitions/I18nData"
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "WorkTypes.FormOfWorkData": {
            "additionalProperties": false,
            "properties": {
                "items": {
                    "items": {
                        "$ref": "#/definitions/WorkTypes.FormOfWorkItemData"
                    },
                    "type": "array"
                },
                "sectionLabel": {
                    "$ref": "#/definitions/I18nData"
                },
                "type": {
                    "type": "string"
                }
            },
            "required": [
                "items"
            ],
            "type": "object"
        },
        "WorkTypes.FormOfWorkItemData": {
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "label": {
                    "$ref": "#/definitions/I18nData"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "WorkTypes.IncipitSummaryData": {
            "additionalProperties": false,
            "properties": {
                "label": {
                    "$ref": "#/definitions/I18nData"
                },
                "value": {
                    "$ref": "#/definitions/I18nData"
                }
            },
            "type": "object"
        },
        "WorkTypes.IncipitsData": {
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "items": {
                    "items": {
                        "$ref": "#/definitions/WorkTypes.IncipitsItemData"
                    },
                    "type": "array"
                },
                "sectionLabel": {
                    "$ref": "#/definitions/I18nData"
                },
                "type": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "WorkTypes.IncipitsItemData": {
            "additionalProperties": false,
            "properties": {
                "encodings": {
                    "items": {
                        "$ref": "#/definitions/WorkTypes.EncodingsData"
                    },
                    "type": "array"
                },
                "id": {
                    "type": "string"
                },
                "label": {
                    "$ref": "#/definitions/I18nData"
                },
                "properties": {
                    "$ref": "#/definitions/WorkTypes.PropertiesData"
                },
                "rendered": {
                    "items": {
                        "$ref": "#/definitions/WorkTypes.RenderedData"
                    },
                    "type": "array"
                },
                "sectionLabel": {
                    "$ref": "#/definitions/I18nData"
                },
                "summary": {
                    "items": {
                        "$ref": "#/definitions/WorkTypes.IncipitSummaryData"
                    },
                    "type": "array"
                },
                "type": {
                    "type": "string"
                }
            },
            "required": [
                "id"
            ],
            "type": "object"
        },
        "WorkTypes.ItemsData": {
            "additionalProperties": false,
            "properties": {
                "relatedTo": {
                    "$ref": "#/definitions/WorkTypes.RelatedToData"
                },
                "relationshipType": {
                    "type": "string"
                },
                "workNumber": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "WorkTypes.PAEData": {
            "additionalProperties": false,
            "properties": {
                "clef": {
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "keysig": {
                    "type": "string"
                },
                "timesig": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "WorkTypes.PartOfData": {
            "additionalProperties": false,
            "properties": {
                "items": {
                    "items": {
                        "$ref": "#/definitions/WorkTypes.ItemsData"
                    },
                    "type": "array"
                },
                "label": {
                    "$ref": "#/definitions/I18nData"
                },
                "type": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "WorkTypes.PropertiesData": {
            "additionalProperties": false,
            "properties": {
                "clef": {
                    "type": "string"
                },
                "keysig": {
                    "type": "string"
                },
                "notation": {
                    "type": "string"
                },
                "timesig": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "WorkTypes.RecordHistoryData": {
            "additionalProperties": false,
            "properties": {
                "created": {
                    "$ref": "#/definitions/WorkTypes.CreatedData"
                },
                "type": {
                    "type": "string"
                },
                "updated": {
                    "$ref": "#/definitions/WorkTypes.UpdatedData"
                }
            },
            "type": "object"
        },
        "WorkTypes.RelatedToData": {
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "label": {
                    "$ref": "#/definitions/I18nData"
                },
                "status": {
                    "$ref": "#/definitions/WorkTypes.StatusData"
                },
                "type": {
                    "type": "string"
                },
                "typeLabel": {
                    "$ref": "#/definitions/I18nData"
                }
            },
            "required": [
                "id",
                "label"
            ],
            "type": "object"
        },
        "WorkTypes.RelationshipsData": {
            "additionalProperties": false,
            "properties": {
                "items": {
                    "items": {
                        "$ref": "#/definitions/WorkTypes.RelationshipsItemData"
                    },
                    "type": "array"
                },
                "sectionLabel": {
                    "$ref": "#/definitions/I18nData"
                }
            },
            "type": "object"
        },
        "WorkTypes.RelationshipsItemData": {
            "additionalProperties": false,
            "properties": {
                "relatedTo": {
                    "$ref": "#/definitions/WorkTypes.RelatedToData"
                },
                "role": {
                    "$ref": "#/definitions/WorkTypes.RoleData"
                }
            },
            "type": "object"
        },
        "WorkTypes.RenderedData": {
            "additionalProperties": false,
            "properties": {
                "data": {
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "WorkTypes.RoleData": {
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "label": {
                    "$ref": "#/definitions/I18nData"
                },
                "value": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "WorkTypes.SourcesData": {
            "additionalProperties": false,
            "properties": {
                "totalItems": {
                    "type": "number"
                },
                "url": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "WorkTypes.StatusData": {
            "additionalProperties": false,
            "properties": {
                "label": {
                    "$ref": "#/definitions/I18nData"
                },
                "value": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "WorkTypes.SummaryData": {
            "additionalProperties": false,
            "properties": {
                "label": {
                    "$ref": "#/definitions/I18nData"
                },
                "value": {
                    "$ref": "#/definitions/I18nData"
                }
            },
            "type": "object"
        },
        "WorkTypes.UpdatedData": {
            "additionalProperties": false,
            "properties": {
                "label": {
                    "$ref": "#/definitions/I18nData"
                },
                "value": {
                    "type": "string"
                }
            },
            "type": "object"
        }
    },
    "properties": {
        "@context": {
            "type": "string"
        },
        "creator": {
            "$ref": "#/definitions/WorkTypes.CreatorData"
        },
        "externalAuthorities": {
            "$ref": "#/definitions/WorkTypes.ExternalAuthoritiesData"
        },
        "formOfWork": {
            "$ref": "#/definitions/WorkTypes.FormOfWorkData"
        },
        "id": {
            "type": "string"
        },
        "incipits": {
            "$ref": "#/definitions/WorkTypes.IncipitsData"
        },
        "label": {
            "$ref": "#/definitions/I18nData"
        },
        "partOf": {
            "$ref": "#/definitions/WorkTypes.PartOfData"
        },
        "recordHistory": {
            "$ref": "#/definitions/WorkTypes.RecordHistoryData"
        },
        "relationships": {
            "$ref": "#/definitions/WorkTypes.RelationshipsData"
        },
        "sources": {
            "$ref": "#/definitions/WorkTypes.SourcesData"
        },
        "summary": {
            "items": {
                "$ref": "#/definitions/WorkTypes.SummaryData"
            },
            "type": "array"
        },
        "type": {
            "type": "string"
        }
    },
    "required": [
        "id",
        "partOf"
    ],
    "type": "object"
}

=== lpugin/rism-online-renderer/test/work.json
{
  "@context": "https://dev.rism.online/api/v1/work.json",
  "id": "https://dev.rism.online/works/32206",
  "type": "rism:Work",
  "label": {
    "none": [
      "Verleih uns Frieden  MWV A 11"
    ]
  },
  "creator": {
    "role": {
      "label": {
        "pl": [
          "Kompozytor / Autor"
        ],
        "en": [
          "Composer/Author"
        ],
        "it": [
          "Compositore/Autore"
        ],
        "fr": [
          "Compositeur/Auteur"
        ],
        "pt": [
          "Compositor/Autor"
        ],
        "de": [
          "Komponist/Autor"
        ],
        "es": [
          "Compositor/Autor"
        ]
      },
      "value": "relators:cre",
      "id": "relators:cre"
    },
    "relatedTo": {
      "id": "https://dev.rism.online/people/88790",
      "label": {
        "none": [
          "Mendelssohn Bartholdy, Felix (1809-1847)"
        ]
      },
      "type": "rism:Person"
    }
  },
  "summary": [
    {
      "label": {
        "pl": [
          "Tonacja lub modus"
        ],
        "en": [
          "Key or mode"
        ],
        "it": [
          "Tonalità, modo"
        ],
        "fr": [
          "Tonalité, mode"
        ],
        "pt": [
          "Tonalidade, modo"
        ],
        "de": [
          "Tonart, Modus"
        ],
        "es": [
          "Tonalidad o modo"
        ]
      },
      "value": {
        "pl": [
          "Es-dur"
        ],
        "en": [
          "E♭ major"
        ],
        "it": [
          "Mi♭ maggiore"
        ],
        "fr": [
          "Mi♭ majeur"
        ],
        "pt": [
          "Mi bemol maior"
        ],
        "de": [
          "Es-Dur"
        ],
        "es": [
          "Mi bemol Mayor"
        ]
      }
    },
    {
      "label": {
        "pl": [
          "Podsumowanie obsady"
        ],
        "en": [
          "Scoring summary"
        ],
        "it": [
          "Organico sintetico"
        ],
        "fr": [
          "Instrumentation condensée"
        ],
        "pt": [
          "Sintese da formação instrumental"
        ],
        "de": [
          "Besetzungshinweis"
        ],
        "es": [
          "Resumen de Plantilla/Orgánico"
        ]
      },
      "value": {
        "none": [
          "V (4), orch"
        ]
      }
    },
    {
      "label": {
        "pl": [
          "Incipit tekstowy"
        ],
        "en": [
          "Text incipit"
        ],
        "it": [
          "Incipit testuale"
        ],
        "fr": [
          "Incipit du texte"
        ],
        "pt": [
          "Incipit literário"
        ],
        "de": [
          "Textincipit"
        ],
        "es": [
          "Íncipit literario"
        ]
      },
      "value": {
        "none": [
          "Verleih uns Frieden gnädiglich"
        ]
      }
    },
    {
      "label": {
        "pl": [
          "Alternatywny tytuł dzieła"
        ],
        "en": [
          "Alternative work title"
        ],
        "it": [
          "Titolo alternativo dell'opera"
        ],
        "fr": [
          "Titre alternatif"
        ],
        "pt": [
          "Título alternativo da obra"
        ],
        "de": [
          "Alternativer Werktitel"
        ],
        "es": [
          "Título alternativo"
        ]
      },
      "value": {
        "pl": [
          "Choral / Gebet „Verleih uns Frieden“ / „Da nobis pacem, Domine“",
          "Da nobis pacem Domine",
          "O salutaris hostia",
          "Gebet",
          "Verleih uns Frieden",
          "Da nobis pacem",
          "Gebet nach Luther'schen Worten",
          "Dona nobis pacem Domine"
        ],
        "en": [
          "Choral / Gebet „Verleih uns Frieden“ / „Da nobis pacem, Domine“",
          "Da nobis pacem Domine",
          "O salutaris hostia",
          "Gebet",
          "Verleih uns Frieden",
          "Da nobis pacem",
          "Gebet nach Luther'schen Worten",
          "Dona nobis pacem Domine"
        ],
        "it": [
          "Choral / Gebet „Verleih uns Frieden“ / „Da nobis pacem, Domine“",
          "Da nobis pacem Domine",
          "O salutaris hostia",
          "Gebet",
          "Verleih uns Frieden",
          "Da nobis pacem",
          "Gebet nach Luther'schen Worten",
          "Dona nobis pacem Domine"
        ],
        "fr": [
          "Choral / Gebet „Verleih uns Frieden“ / „Da nobis pacem, Domine“",
          "Da nobis pacem Domine",
          "O salutaris hostia",
          "Gebet",
          "Verleih uns Frieden",
          "Da nobis pacem",
          "Gebet nach Luther'schen Worten",
          "Dona nobis pacem Domine"
        ],
        "pt": [
          "Choral / Gebet „Verleih uns Frieden“ / „Da nobis pacem, Domine“",
          "Da nobis pacem Domine",
          "O salutaris hostia",
          "Gebet",
          "Verleih uns Frieden",
          "Da nobis pacem",
          "Gebet nach Luther'schen Worten",
          "Dona nobis pacem Domine"
        ],
        "de": [
          "Choral / Gebet „Verleih uns Frieden“ / „Da nobis pacem, Domine“",
          "Da nobis pacem Domine",
          "O salutaris hostia",
          "Gebet",
          "Verleih uns Frieden",
          "Da nobis pacem",
          "Gebet nach Luther'schen Worten",
          "Dona nobis pacem Domine"
        ],
        "es": [
          "Choral / Gebet „Verleih uns Frieden“ / „Da nobis pacem, Domine“",
          "Da nobis pacem Domine",
          "O salutaris hostia",
          "Gebet",
          "Verleih uns Frieden",
          "Da nobis pacem",
          "Gebet nach Luther'schen Worten",
          "Dona nobis pacem Domine"
        ]
      }
    },
    {
      "label": {
        "pl": [
          "Daty"
        ],
        "en": [
          "Dates"
        ],
        "it": [
          "Date"
        ],
        "fr": [
          "Dates"
        ],
        "pt": [
          "Datas"
        ],
        "de": [
          "Datierungen"
        ],
        "es": [
          "Fechas"
        ]
      },
      "value": {
        "none": [
          "1831 (10. Februar 1831)"
        ]
      }
    },
    {
      "label": {
        "pl": [
          "RISM ID"
        ],
        "en": [
          "RISM ID number"
        ],
        "it": [
          "Numero documento RISM"
        ],
        "fr": [
          "No. RISM"
        ],
        "pt": [
          "Número ID RISM"
        ],
        "de": [
          "RISM Dokumentnummer"
        ],
        "es": [
          "Número de ID de RISM"
        ]
      },
      "value": {
        "none": [
          "works/32206"
        ]
      }
    }
  ],
  "partOf": {
    "label": {
      "pl": [
        "Jest częścią…"
      ],
      "en": [
        "Item part of"
      ],
      "it": [
        "Fa parte di"
      ],
      "fr": [
        "Fait partie de"
      ],
      "pt": [
        "Item parte de"
      ],
      "de": [
        "In"
      ],
      "es": [
        "Ítem integrante de"
      ]
    },
    "type": "rism:PartOfSection",
    "items": [
      {
        "relationshipType": "rism:PrimaryPartOf",
        "relatedTo": {
          "id": "https://dev.rism.online/publications/30025296",
          "label": {
            "none": [
              "Felix Mendelssohn Bartholdy - thematisch-systematisches Verzeichnis der musikalischen Werke (MWV)"
            ]
          },
          "type": "rism:Publication",
          "typeLabel": {
            "pl": [
              "Katalog dzieł"
            ],
            "en": [
              "Work catalog"
            ],
            "it": [
              "Catalogo delle opere"
            ],
            "fr": [
              "Catalogue des œuvres"
            ],
            "pt": [
              "Catálogo da obra"
            ],
            "de": [
              "Werkkatalog"
            ],
            "es": [
              "Catálogos de trabajo"
            ]
          },
          "status": {
            "label": {
              "pl": [
                "Kompletne"
              ],
              "en": [
                "Completed"
              ],
              "it": [
                "Completato"
              ],
              "fr": [
                "Terminé"
              ],
              "pt": [
                "Concluído"
              ],
              "de": [
                "Abgeschlossen"
              ],
              "es": [
                "Completado"
              ]
            },
            "value": "completed"
          }
        },
        "workNumber": "MWV A 11"
      }
    ]
  },
  "recordHistory": {
    "type": "rism:RecordHistory",
    "created": {
      "label": {
        "pl": [
          "Data utworzenia"
        ],
        "en": [
          "Created on"
        ],
        "it": [
          "Data di creazione"
        ],
        "fr": [
          "Date de création"
        ],
        "pt": [
          "Criado em"
        ],
        "de": [
          "Erstellungsdatum"
        ],
        "es": [
          "Fecha de creación"
        ]
      },
      "value": "2023-04-26T06:31:48Z"
    },
    "updated": {
      "label": {
        "pl": [
          "Ostatnia modyfikacja"
        ],
        "en": [
          "Last modification"
        ],
        "it": [
          "Ultima modifica"
        ],
        "fr": [
          "Dernière modification"
        ],
        "pt": [
          "Última modificação"
        ],
        "de": [
          "Letzte Änderung"
        ],
        "es": [
          "Fecha de modificación"
        ]
      },
      "value": "2025-09-08T11:23:45Z"
    }
  },
  "incipits": {
    "id": "https://dev.rism.online/works/32206/incipits",
    "sectionLabel": {
      "pl": [
        "Incipity"
      ],
      "en": [
        "Incipits"
      ],
      "it": [
        "Incipit"
      ],
      "fr": [
        "Incipits"
      ],
      "pt": [
        "Incipit"
      ],
      "de": [
        "Incipits"
      ],
      "es": [
        "Íncipits"
      ]
    },
    "type": "rism:WorkIncipitsSection",
    "items": [
      {
